FROM node:14.18.1-alpine

WORKDIR /app

COPY nest/package*.json ./
COPY nest/tsconfig*.json ./

RUN npm install
RUN npm install --save-dev

RUN npm install -g nodemon
RUN npm install -g ts-node

EXPOSE 3000

CMD ["npm","run","start:dev"]

