version: '3.2'
services:
  # mongo:
  #   container_name: mongo
  #   build:
  #     dockerfile: ./mongo/
  #   restart: always
  #   environment:
  #     - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  #     - DB_USER=user
  #     - DB_PWD=123123
  #   ports:
  #     - ${MONGO_PORT}:27017
  #   volumes:
  #     - ./mongo/data:/data/db
  #     - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  #   networks:
  #     - app-network
  #   env_file:
  #     - ./mongo/.env
  nest:
    container_name: nest
    build:
      context: ./nest
      dockerfile: ./dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./nest/src:/app/src
    #   - ./nest/package.json:/app/package.json
    #   - ./nest/package-lock.json:/app/package-lock.json
    #   - ./nest/tsconfig.json:/app/tsconfig.json
    #   - ./nest/tsconfig.build.json:/app/tsconfig.build.json

    # depends_on:
    #   - mongo
    # networks:
    #   - app-network
    env_file:
      - ./nest/.env
# networks:
#   app-network:
#     driver: bridge
