version: '3.2'
services:
  mongodb:
    build:
      context: ./
      dockerfile: ./mongo/dockerfile
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - DB_USER=user
      - DB_PWD=123123
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    # networks:
    #   - app-network
    env_file:
      - .env
#   nest:
#     build:
#       context: ../
#       dockerfile: ./docker/dockerfile
#     container_name: nest
#     ports:
#       - 3000:3000
#     volumes:
#       - ../src:/app/src
#     depends_on:
#       - mongodb
#     networks:
#       - app-network
#     env_file:
#       - ../.env

# networks:
#   app-network:
#     driver: bridge
