FROM node:12.20.0

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY .env ./

RUN npm install
RUN npm install --save-dev

RUN npm install -g nodemon
RUN npm install -g ts-node

EXPOSE 3000

CMD ["npm","run","start:dev"]

